name: finanzapp
description: Aplicación para registro de usuarios y control de gastos.
version: 2.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.9.0

  # Otros paquetes útiles si los deseas (comentados por defecto)
  # provider: ^6.0.5

dev_dependencies:
  flutter_launcher_icons: ^0.9.2

flutter_test:
  sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"  # Ruta del archivo PNG

flutter:
  uses-material-design: true

  # Si tienes un logo o imágenes en assets, descomenta y ajusta esta sección:
  assets:
    - assets/logo.png
